name: tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3

            -   name: Install Dependencies
                run: |
                    sudo apt update
                    sudo apt install -y \
                        imagemagick
                    npm install
                    cd IntegrationTests
                    npm install

            -   name: Install Swift
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.1.2-release/ubuntu2404/swift-6.1.2-RELEASE"
                    swift-id: "swift-6.1.2-RELEASE-ubuntu24.04"

            -   name: Install Swift WebAssembly SDK
                env:
                    SWIFTWASM_VERSION: "6.1-RELEASE"
                    SWIFTWASM_TRIPLE: "wasm32-unknown-wasip1-threads"
                run: |
                    swift sdk install \
                    "https://github.com/swiftwasm/swift/releases/download/swift-wasm-$SWIFTWASM_VERSION/swift-wasm-$SWIFTWASM_VERSION-$SWIFTWASM_TRIPLE.artifactbundle.zip" \
                    --checksum 0dd273be28741f8e1eb00682c39bdc956361ed24b5572e183dd8a4e9d1c5f6ec

            -   name: Run tests
                run: Scripts/TestAll
