name: tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        steps:
            -   name: ğŸ® Checkout repository ğŸ®
                uses: actions/checkout@v3

            -   name: ğŸ® Install Dependencies ğŸ®
                run: |
                    sudo apt update
                    sudo apt install -y \
                        imagemagick
                    npm install
                    cd IntegrationTests
                    npm install

            -   name: ğŸ® Install Swift ğŸ®
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.1.2-release/ubuntu2404/swift-6.1.2-RELEASE"
                    swift-id: "swift-6.1.2-RELEASE-ubuntu24.04"

            -   name: ğŸ® Install Swift WebAssembly SDK ğŸ®
                env:
                    SWIFTWASM_VERSION: "6.1-RELEASE"
                    SWIFTWASM_TRIPLE: "wasm32-unknown-wasip1-threads"
                run: |
                    swift sdk install \
                    "https://github.com/swiftwasm/swift/releases/download/swift-wasm-$SWIFTWASM_VERSION/swift-wasm-$SWIFTWASM_VERSION-$SWIFTWASM_TRIPLE.artifactbundle.zip" \
                    --checksum 0dd273be28741f8e1eb00682c39bdc956361ed24b5572e183dd8a4e9d1c5f6ec

            -   name: ğŸ® Build and run unit tests ğŸ®
                run: swift test

            -   name: ğŸ® Build integration tests ğŸ®
                run: |
                    Scripts/Build -s
                    Scripts/Build -j
                    Scripts/Build -x
                    Scripts/Build -i -c release

            -   name: ğŸ® Run integration tests ğŸ®
                run: |
                    cd IntegrationTests
                    npx tsc
                    npm test
