name: tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04
        steps:
            -   name: ğŸ® Checkout repository ğŸ®
                uses: actions/checkout@v3

            -   name: ğŸ® Install Dependencies ğŸ®
                run: |
                    sudo apt update
                    sudo apt install -y \
                        imagemagick
                    npm install
                    cd Tests
                    npm install

            -   name: ğŸ® Install Swift ğŸ®
                uses: tayloraswift/swift-install-action@master
                with:
                    swift-prefix: "swift-6.3-branch/ubuntu2404/swift-6.3-DEVELOPMENT-SNAPSHOT-2025-12-13-a"
                    swift-id: "swift-6.3-DEVELOPMENT-SNAPSHOT-2025-12-13-a-ubuntu24.04"

            -   name: ğŸ® Install Swift WebAssembly SDK ğŸ®
                env:
                    SWIFTWASM_VERSION: "6.3-SNAPSHOT-2025-12-13-a"
                    SWIFTWASM_TRIPLE: "wasm32-unknown-wasip1-threads"
                run: |
                    swift sdk install \
                    "https://github.com/swiftwasm/swift/releases/download/swift-wasm-$SWIFTWASM_VERSION/swift-wasm-$SWIFTWASM_VERSION-$SWIFTWASM_TRIPLE.artifactbundle.zip" \
                    --checksum c49407947f6d91809ad57a83a2482062eec6a50cc0e22e6fd6eb01d6de6925a5

            -   name: ğŸ® Build and run unit tests ğŸ®
                run: swift test

            -   name: ğŸ® Build and run engine tests ğŸ®
                run: |
                    Scripts/Build -j
                    Scripts/Build -l -c release
                    Scripts/RunEngineTests

            -   name: ğŸ® Build integration tests ğŸ®
                run: |
                    Scripts/Build -s
                    Scripts/Build -x
                    Scripts/Build -i -c release

            -   name: ğŸ® Run integration tests ğŸ®
                run: Scripts/RunIntegrationTests
