name: tests

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    Linux:
        runs-on: ubuntu-24.04
        name: host
        steps:
            -   name: ğŸ® Checkout ğŸ®
                uses: actions/checkout@v4

            -   name: ğŸ® Install shared dependencies ğŸ®
                uses: ./.github/actions/setup

            -   name: ğŸ® Build and run unit tests ğŸ®
                run: swift test

            -   name: ğŸ® Build and run engine tests ğŸ®
                run: |
                    Scripts/Build -j
                    Scripts/Build -l -c release
                    Scripts/RunEngineTests

    WebAssembly:
        runs-on: ubuntu-24.04
        name: wasm
        steps:
            -   name: ğŸ® Checkout ğŸ®
                uses: actions/checkout@v4

            -   name: ğŸ® Install shared dependencies ğŸ®
                uses: ./.github/actions/setup

            -   name: ğŸ® Install Swift WebAssembly SDK ğŸ®
                env:
                    SWIFTWASM_VERSION: "6.3-SNAPSHOT-2025-12-13-a"
                    SWIFTWASM_TRIPLE: "wasm32-unknown-wasip1-threads"
                run: |
                    swift sdk install \
                    "https://github.com/swiftwasm/swift/releases/download/swift-wasm-$SWIFTWASM_VERSION/swift-wasm-$SWIFTWASM_VERSION-$SWIFTWASM_TRIPLE.artifactbundle.zip" \
                    --checksum c49407947f6d91809ad57a83a2482062eec6a50cc0e22e6fd6eb01d6de6925a5

            #   note: top-level node dependencies already installed in setup action
            -   name: ğŸ® Install testing dependencies ğŸ®
                run: |
                    sudo apt update
                    sudo apt install -y \
                        imagemagick
                    cd Tests
                    npm install

            -   name: ğŸ® Build integration tests ğŸ®
                run: |
                    Scripts/Build -j
                    Scripts/Build -s
                    Scripts/Build -x
                    Scripts/Build -i -c release

            -   name: ğŸ® Run integration tests ğŸ®
                run: Scripts/RunIntegrationTests
